// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtoEF.Data;

namespace ProtoEF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180829112005_addPortTable")]
    partial class addPortTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProtoEF.Models.Port", b =>
                {
                    b.Property<int>("PortId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PortType")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasMaxLength(1);

                    b.HasKey("PortId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("ProtoEF.Models.Vessel", b =>
                {
                    b.Property<int>("VesselId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("VesselId");

                    b.ToTable("Vessels");
                });
#pragma warning restore 612, 618
        }
    }
}
